In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad=True)

In [3]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [4]:
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [10]:
print(type(y))# Backpropogation

<class 'torch.Tensor'>


In [12]:
y.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [13]:
x.grad

tensor(93.)

In [14]:
x = torch.tensor([
    [1., 2., 3.],
    [3., 2., 1.]
], requires_grad=True)

In [15]:
y = 3*x + 2

In [16]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [17]:
z = 2*y**2

In [18]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [19]:
out = z.mean()

In [21]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [22]:
out.backward()

In [23]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
