In [3]:
import torch 
import numpy as np 

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

1. Tensor creation

In [15]:
tensor_array = torch.tensor(arr)

In [27]:
torch.ones(3, 4, 5, dtype=torch.int64)

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]])

In [29]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [31]:
x = torch.arange(6).reshape(3, 2)

In [38]:
x[2, 1]

tensor(5)

In [39]:
x[:,1]

tensor([1, 3, 5])

In [40]:
x = torch.arange(10)

In [42]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [52]:
x = x.reshape(2, 5)

In [53]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [55]:
x = torch.arange(10)

In [56]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [57]:
z = x.view(2, 5)

In [58]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [59]:
x[0] = 313

In [60]:
z

tensor([[313,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [61]:
x = torch.arange(10)

In [62]:
x.shape

torch.Size([10])

In [64]:
# INFER what the 2nd dimension 
x.view(5, -1)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [66]:
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [67]:
a = torch.tensor([1., 2., 3.])

In [68]:
b = torch.tensor([4., 5., 6.])

In [69]:
a * b

tensor([ 4., 10., 18.])

In [70]:
a / b

tensor([0.2500, 0.4000, 0.5000])

In [71]:
a - b

tensor([-3., -3., -3.])

In [72]:
torch.add(a, b)

tensor([5., 7., 9.])

In [73]:
torch.multiply(a, b)

tensor([ 4., 10., 18.])

In [74]:
a.add_(b)
# Reassignment

tensor([5., 7., 9.])

In [75]:
a

tensor([5., 7., 9.])

In [79]:
a.mul_(b)

tensor([ 80., 175., 324.])

In [80]:
a

tensor([ 80., 175., 324.])

In [81]:
a.dot(b)

tensor(3139.)

In [85]:
a = torch.tensor([[0, 2, 4], [1, 3, 5]])
b = torch.tensor([[6, 7], [3, 4], [6, 9]])
print(a)
print(b)

tensor([[0, 2, 4],
        [1, 3, 5]])
tensor([[6, 7],
        [3, 4],
        [6, 9]])


In [86]:
a.mm(b)
# matrix multiplication

tensor([[30, 44],
        [45, 64]])

In [87]:
a @ b

tensor([[30, 44],
        [45, 64]])

In [91]:
x = torch.tensor([1., 4., 5.])

In [92]:
x.norm()

tensor(6.4807)